### ISSUE TITLE
Track Packages in Migration Process

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#38]
**What would you like to be added**:

---
> [!CAUTION]
The failure of these packages may be due to a bug in the workflow.
Failed on arm #59 
- [ ] #48
Missing build-deps.
Failed on arm: https://github.com/gardenlinux/package-aws-kms-pkcs11/actions/runs/7084215581/job/19278071792
- [x] package-ena-dkms - don't need anymore 
- [x] package-glibc - we builds supported version in gitlab-ci, so this repo can be skip for now.
Failed on arm https://github.com/gardenlinux/package-glibc/actions/runs/7084218037/job/19280380863
- [x] package-libyang - can be drop as duplicated with `package-libyang2` that we currently using.
- [x] package-podman-toolbox - don't need anymore
- [x] package-python3.10 - obsoleted by python3.11 

---
> [!Warning]
These packages are available in Debian but they contain a `debian/` directory in their repo. The changes should be converted into `patches/` instead:
- [x] package-ferm
- [x] package-kpatch
- [x] package-libyang2 - synced from `package-libyang`, may drop `package-libyang` now.
- [x] package-microsoft-authentication-library-for-python
- [x] #42 - builds with nocheck
- [x] package-openssl

---
> [!NOTE]  
Packages builds both locally and workflow:
- [x] package-aws-sdk-cpp
- [x] package-cloud-init
- [x] package-containerd
- [x] package-containerd-1.7
- [x] package-curl
- [x] package-cyrus-sasl2
- [x] package-docker-machine
- [x] package-docker.io
- [x] package-frr
- [x] package-gardenlinux-repo-manager
- [x] package-gardenlinux-selinux-module
- [x] package-htop
- [x] package-ignition
- [x] package-iproute2
- [x] package-libpam-ssh
- [x] package-neofetch
- [x] package-onmetal-image
- [x] #50 - builds with nocheck
- [x] package-oras
- [x] package-pam
- [x] #45 - builds with nocheck
- [x] package-python3-defaults
- [x] package-python3.11
- [x] #46
- [x] package-runc
- [x] package-selinux-basics
- [x] package-selinux-policy-targeted-fedora
- [x] #49
- [x] package-sudosh2
- [x] #44
- [x] package-systemd
- [x] package-tar

---
**Why is this needed**:
As part of the ongoing migration process, we need to track all the packages being migrated to ensure a smooth transition.

**Comment by nkraetzschmar** [comment]
Please check that these are all actually migrated to the new build system and we are not accidentally missing modifications.

21 package repos still have a `debian` folder instead of just `patches` for package migration to be considered *done* we need to ensure that the debian folder used by the old build system does not include any significant differences to the debian folder upstream, or if it does these changes need to be made into patches.

**List of package repos still containing a debian folder:**
```
package-aws-kms-pkcs11
package-aws-sdk-cpp
package-containerd-1
package-docker-machine
package-ena-dkms
package-ferm
package-gardenlinux-repo-manager
package-gardenlinux-selinux-module
package-glibc
package-kpatch
package-libstoragemgmt
package-libyang
package-microsoft-authentication-library-for-python
package-onmetal-image
package-openssh
package-openssl
package-oras
package-selinux-policy-targeted-fedora
package-sops
package-sudosh2
```

**Comment by alee-cd** [comment]
Thank you for pointing these out.
I checked these packages are not available in Debian so that we have to ship our own `debian/`:
```
package-aws-kms-pkcs11
package-aws-sdk-cpp
package-containerd-1.7
package-docker-machine
package-ena-dkms
package-gardenlinux-repo-manager
package-gardenlinux-selinux-module
package-libstoragemgmt
package-onmetal-image
package-oras
package-selinux-policy-targeted-fedora
package-sops
package-sudosh2
```

Packages that available in Debian so we need to double check if we can drop the `debian/` in our repo by provide `patches/`:
```
package-ferm
package-glibc
package-kpatch
package-libyang2
package-microsoft-authentication-library-for-python
package-openssh
package-openssl
```

**Comment by alee-cd** [comment]
Just checked the README.md from `libyang` that we need to build the latest version `libyang` for `frr` version `0.9`. And the the latest upstream release is version `2.1.128`. So we better switch to use `package-libyang2` repo instead.

**Comment by nanory** [comment]
All packages have been migrated. There are problems with `aws-kms-pkcs11` but they are tracked in #48 
Therefore, I'm closing this issue here.
